### ISSUE TITLE
Guide: Write Network celebration/testimonials

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#115]
For 2016 Festival Guide. Write Network celebration/testimonials

Include: 
- Quotes from attendees & Ravensbourne about what they get from it

Notes: 
- This content can be space-filler. Doesn't need it's own page/section in the guide.
- Can pull from [8/24 email](https://docs.google.com/document/d/1dSlVkFYnYEeQfqYHDM9dviTq1riQSfg0mawRaX0azBs/edit)

**Comment by edrushka** [comment]
@Saallen @marcwalsh can we draw up a small shortlist of people to get testimonials from?

**Comment by edrushka** [comment]
“There is something for everyone to do and learn at Mozfest. Mozfest allows you to pick up something completely new and dive in fully.”
 —Hera Hussain

"MozFest is designed to be like the web: a place where you can make things that matter."
—Sam Dyson

"My favourite part of Mozfest has always been the uniqueness and diversity of the people in the room."
—Amira Dhalla

**Comment by edrushka** [comment]
@ldecoursy do you have any testimonials from our network about the value of MozFest?

**Comment by edrushka** [comment]
@omnignorant do you have any quotes from Marina about participating at MozFest?

**Comment by ldecoursy** [comment]
@edrushka  here are a few from recent Mozilla Learning community blog spotlights: 

See https://blog.webmaker.org/august-community-spotlight-hive-manchester

How did Hive Manchester get its start?

Hive Manchester was inspired by the other Hive communities we met over several years at Mozfest. Steven Flower and I were already working in digital access and skills in Manchester and shared many of Mozilla’s aims, so we decided to found Hive Manchester together. At Mozfest 2014, a Hive was officially set up, and just before Mozfest 2015 we gained funding from Manchester City Council to run Hive as a ‘pilot project’ for one year. That has been extended by a local authority for another sixth months and are actively seeking partnership with other local organizations.

Also https://blog.webmaker.org/june-community-spotlight-yousef-alam

What is your background with the web? With Mozilla?

I went to the Mozilla Festival back in 2012 because it was cheap for under-16s and seemed interesting. The enthusiasm, knowledge and pure passion for the open web was what got me started contributing to Mozilla. I started out answering questions and writing documentation about Firefox on the support website before moving onto Community Operations, a small team which maintains community websites and services, with some monthly newsletter coding and Firefox OS participation in between.

Here's a post from 2014 that has some quotes https://blog.webmaker.org/your-stories-from-mozfest-2014s-community-building-track

**Comment by edrushka** [comment]
@carrie-ann @kristinashu here are a variety of testimonials for use in the Festival Guide. Including these quotes is not a requirement - they are simply here if you need them.

---

There is something for everyone to do and learn at Mozfest. Mozfest allows you to pick up something completely new and dive in fully.
—Hera Hussain [from email]

MozFest is designed to be like the web: a place where you can make things that matter.
—Sam Dyson [from email]

My favourite part of Mozfest has always been the uniqueness and diversity of the people in the room.
—Amira Dhalla [from email]

Ensuring students are web literate should be a priority. MozFest has given me the courage to step out of my comfort zone and bring webmaking into the classroom.
— Gina Tesoriero  [from 2014 infographic]

We need to move beyond a US-centric model for internet advocacy. Countries like South Africa have — Kelsey Wiens [from 2014 infographic]

Emerging markets have different needs. Local producers and creators have the potential to serve themselves; they just need a little bit of tech knowledge.
— Chris Locke [from 2014 infographic]

Mozilla is about building the open platform, building opportunity and empowerment for all of us. And it is the activities that happen here and come out of MozFest that really prove how much hope there is for success.
— Mitchell Baker [from video]

It's great to be around a community of people who all have the same idea: to build a better internet and take control.
— Raegan MacDonald [from video]

Hive Manchester was inspired by the other Hive communities we met over several years at Mozfest. Steven Flower and I were already working in digital access and skills in Manchester and shared many of Mozilla’s aims, so we decided to found Hive Manchester together. At Mozfest 2014, a Hive was officially set up, and just before Mozfest 2015 we gained funding from Manchester City Council to run Hive as a ‘pilot project’ for one year. That has been extended by a local authority for another sixth months and are actively seeking partnership with other local organizations.
— Damian Payton [from community spotlight]

I went to the Mozilla Festival back in 2012 because it was cheap for under-16s and seemed interesting. The enthusiasm, knowledge and pure passion for the open web was what got me started contributing to Mozilla. I started out answering questions and writing documentation about Firefox on the support website before moving onto Community Operations, a small team which maintains community websites and services, with some monthly newsletter coding and Firefox OS participation in between.
— Yousef Alam  [from community spotlight]

**Comment by edrushka** [comment]
Closing. Pull text from final festival guide InDesign file. Content in this ticket has not been through final proof-reading.
