### ISSUE TITLE
Ravensbourne Network Requirements

### ISSUE THREAD

**Issue by marcwalsh-zz** [MozillaFoundation/Mozfest2016_production#125]
Ensure MozFest's networking needs are met by Ravensbourne.
- [x] Feedback from last year 
- [x] Send feedback and initial needs to Ravensbourne
- [x] Track specialist tech being brought onsite.
## 

What's needed from Ravensbourne:
- [x] Bandwidth for 1600+ people with 3+ devices
- [x] Allocated bandwidth for live streaming
- [x] Additional access points on Level 4 and Level 6 
- [x] Process for collecting mac addresses for wired network
- [x] Sign on details and process for wireless and wired network
- [x] Password requirements for RaveEvents network
- [x] Ensuring that equipment can't be played with by participants

**Comment by Saallen** [comment]
As per the latest conversation with Ravens IT team:
- Pay attention on floors 4 and 6 where there was a need to add extra access points during the last year's event due to an increased number of users on these floors
- Need for helpdesk laptops to have local admin rights
- One floor port in Walker Space to be used for streaming

I am working on performing a service test across all floors however I am aware that the RaveEvents service has been stable with no service affecting issues reported. I will also focus on floors 4 and 6 and take relevant action before the event and I will ensure support will be available for the duration of the event shall immediate action is required.

Regarding laptop access rights I will raise it with helpdesk.
