### ISSUE TITLE
Design for screens around the building

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#170]
Need visuals for screens around the building. These could be animated or still.

Slides content:
- general MozFest2016
- One Web
- promo for Dialogues and Debates Speaker Series in Walker Space on the Ground Level
- #mozhelp (Tweet #MozHelp or visit the Info Desk on Level 5)
- WiFi (RaveEvents, Password: mozfest16)
- schedule app (mzl.la/sched)
- Connect (#MozFest on Twitter, IG, Flickr and mzl.la/pulse)

Style guide: https://drive.google.com/open?id=0B2irLVDJivhLNUJMb3hGN2JIM0U

Related to: stage slides #86 and #87
Sabrina's slide backgrounds https://drive.google.com/open?id=1ztrY9GBVc10nSUFFXxE1d0UZZDRNRhCAZ9-cUfz60a0

Social media posts #84
Tais' social media images https://drive.google.com/open?id=0B2irLVDJivhLV1BISjNybTVZUUE

Last year's video: https://drive.google.com/open?id=0BzfN9sXlOXt1emY2MHA1ZzIzSTA
and stills: https://drive.google.com/open?id=0B20-0lpP23c0OXM2OXEtbE5DM00

**Comment by kristinashu** [comment]
@edrushka any other content we would need to include?

**Comment by edrushka** [comment]
Perhaps #mozhelp and the network/wifi information.

cc @marcwalsh

**Comment by kristinashu** [comment]
We are lucky get some @natalieworth skills on this!

cc @sabrinang since there will be a lot of overlap with the presenter slides.

**Comment by edrushka** [comment]
Woooooooo YAH NATALIE!!! 🎆 

Love what @taisdesouzalessa has been working on in #84 - these would be great content for the venue screens.

**Comment by edrushka** [comment]
For reference, our official release on the Speaker Series. This info is now public: https://medium.com/mozilla-festival/everything-you-need-to-know-about-mozfests-speaker-series-af8eb8f186bf#.y2pscukes and can be used in the slides/screens.

**Comment by kristinashu** [comment]
@edrushka would you be able to give more guidance for copy? As in, what exactly the slides should say?

**Comment by edrushka** [comment]
Speaker Name
Title or subject of talk
Time of their talk
Location: Walker Space Ground Floor

**Comment by natalieworth** [comment]
@kristinashu @sabrinang @edrushka For the 'speaker section,' should we list each speaker individually and rotate that? e.g.:

Brian Behlendorf // @brianbehlendorf
Executive Director, Hyperledger Project
“Bringing Back the Decentralized Web, with Blockchains and Other New Tools”
Speaking Saturday, Oct. 29 at 11:15 a.m.
Location: Walker Space Ground Floor

**Comment by kristinashu** [comment]
@edrushka do we need to highlight specific speakers on these animated screens or just a more general call out that there are Dialogues and Debates Speaker Series in Walker Space on the Ground Level.

**Comment by natalieworth** [comment]
@kristinashu  @edrushka Time-wise a general callout would be better and set a nice atmospheric tone. I think an issue with the one last year was that it's a bit odd having the Saturday sections still displayed when they have ended.

**Comment by edrushka** [comment]
I was going to say specific speakers and times but Natalie makes a good point. Can there be a middle ground where we highlight speakers names and/or faces and/or speech titles, and indicate it's in the walker space? 

We should be sure to use the phrase "Dialogues and Debates" because that's what they need to know to find more info in the schedule app or guide.

**Comment by kristinashu** [comment]
@natalieworth before you do the motion work, could you please share stills of the screens so we can review the info?

**Comment by natalieworth** [comment]
Hey @kristinashu @sabrinang @edrushka @xmatthewx Was able to get a start on this last week (before board slides took over :)! ) I am working on it this afternoon, but have an intro animation done. I am thinking of having the order listed above (on loop).
Some still shots:
![mozfest_separated_logo_v1_00013](https://cloud.githubusercontent.com/assets/14876567/19496693/8410cb80-953d-11e6-8ad9-06629db5eeb4.png)
![mozfest_separated_logo_v1_00067](https://cloud.githubusercontent.com/assets/14876567/19496700/8ede5c62-953d-11e6-9ef1-04167be174d0.png)
![mozfest_separated_logo_v1_00245](https://cloud.githubusercontent.com/assets/14876567/19496708/970fd956-953d-11e6-8566-54ef971c4e98.png)
![mozfest_separated_logo_v1_00337](https://cloud.githubusercontent.com/assets/14876567/19496711/9d537a7a-953d-11e6-81c3-1178b4255618.png)
![mozfest_separated_logo_v1_00366](https://cloud.githubusercontent.com/assets/14876567/19496722/a30c1c2e-953d-11e6-9ac6-e5f6c7bd761d.png)
![mozfest_separated_logo_v1_00389](https://cloud.githubusercontent.com/assets/14876567/19496727/a7271f84-953d-11e6-9cad-472d9dde3aa8.png)
![mozfest_separated_logo_v1_00472](https://cloud.githubusercontent.com/assets/14876567/19496731/acdd879c-953d-11e6-8c2a-397b542d928a.png)

**Comment by natalieworth** [comment]
@kristinashu @xmatthewx @sabrinang @edrushka 
Rough video draft of these are here: https://drive.google.com/drive/u/1/folders/0B20-0lpP23c0ektzY284SWNsUDA

**Comment by kristinashu** [comment]
Wow these are going to be sweet! Love the 3D triangles!

**Comment by natalieworth** [comment]
Okay, so I have an idea for speaker series slides @edrushka @sabrinang @kristinashu. I'm thinking that it could instead just remain one slide and then rotate on the right through the different speakers. It's less work for me and I think it'd be a lot more comprehendable for the audience instead of having to rotate through a bunch of slides that only feature 1 speaker/ per slide. Let me know what you think of this:
<img width="959" alt="screen shot 2016-10-19 at 3 37 58 pm" src="https://cloud.githubusercontent.com/assets/14876567/19540116/1f43ac56-9612-11e6-885e-710aea2ea6a9.png">

**Comment by natalieworth** [comment]
So the right would rotate kind of like this example at the 18 second mark:
https://videohive.net/item/glitch-opener/17462771?s_rank=91

**Comment by natalieworth** [comment]
Oh! also let me know what you think about the design @kristinashu @sabrinang I pulled from the dialogue page in the booklet/ guide to try and keep consistent between the 2....?

**Comment by kristinashu** [comment]
Sounds good to me! I would just reduce the amount of text (remove Twitter handle and their Topic) if that's ok with @edrushka.

**Comment by natalieworth** [comment]
@edrushka @kristinashu @sabrinang Or...to save on time too for this I could just condense it as more of a 'feature' / ad for the dialogues and speakers since it is in the festival guide. I'm assuming that people won't necessarily be relying—but instead more the website, schedule app, and physical guide/ posters for anything more informational. Here's what I'm thinking (we could just scroll through the different speakers without having to give specific times):
<img width="956" alt="screen shot 2016-10-19 at 4 37 36 pm" src="https://cloud.githubusercontent.com/assets/14876567/19541383/a2ff2914-961a-11e6-8f41-402f2121473e.png">

**Comment by kristinashu** [comment]
I like that idea since the times could change at the last minute, and if it's cool with Erika.

**Comment by natalieworth** [comment]
@edrushka @sabrinang @kristinashu Mozhelp:
We could do "need help?" instead of "lost?" maybe?

<img width="478" alt="screen shot 2016-10-19 at 5 26 36 pm" src="https://cloud.githubusercontent.com/assets/14876567/19542229/51f0f708-9621-11e6-8a33-8493819ead5a.png">
<img width="478" alt="screen shot 2016-10-19 at 5 27 07 pm" src="https://cloud.githubusercontent.com/assets/14876567/19542228/51f0af50-9621-11e6-823d-bd41bf5200a3.png">

**Comment by natalieworth** [comment]
@edrushka The only other things I need confirmed for this are specific content for:
1. schedule app (mzl.la/sched)
2. Connect (#MozFest on Twitter, IG, Flickr and mzl.la/pulse)
and then if the #mozhelp copy is okay above along with the speaker slides

**Comment by edrushka** [comment]
Hey @natalieworth thanks for working on this!

For the D&D slides, let's not put the time - it might change and we def. don't want to display incorrect information. The content in your feature/ad treatment above looks good. I defer to @kristinashu on design.

Yes, confirming the app is mzl.la/sched

Yes, confirming the social hashtag is # MozFest (no space, GH won't let me write this properly)

No, MozHelp slide should say  Help Desk instead of Info Desk, so....
visit the Help Desk on Level 5

**Comment by marcwalsh-zz** [comment]
Hey @natalieworth - Just to let you know that the video slides need to be exported as 1920x1080 H.264 files please, preferably without a crazy high bitrate! :)

**Comment by marcwalsh-zz** [comment]
@natalieworth - Can I get a test of the file as soon as you have something ready to make sure that the export format is correct please?

**Comment by natalieworth** [comment]
@marcwalsh For sure—I'll export something by this afternoon

**Comment by natalieworth** [comment]
@sabrinang @marcwalsh @kristinashu @edrushka Here's draft version. Feel free to post any changes here. I have to fix the 'Dialogues and Debates' section since the motion gets a bit weird there, but let me know what you think! :) @marcwalsh Feel free to text this output to make sure it will work on the screens and I can provide you with a final file tomorrow.
Thanks
Link is here: https://drive.google.com/file/d/0B20-0lpP23c0dmJBNjFSc1hSMjA/view

**Comment by edrushka** [comment]
@marcwalsh ❗️ Important please confirm WIFI info (network name & password) ❗️

**Comment by marcwalsh-zz** [comment]
SSID: Rave
Password: mozfest16

**Comment by xmatthewx** [comment]
Amazing stuff @natalieworth!
