### ISSUE TITLE
Print vinyl

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#177]
Let's use this issue to develop our game plan. 

cc @marcwalsh @kristinashu @edrushka @Saallen

**Comment by xmatthewx** [comment]
@lovegushwa mentioned that Ravensbourne might have purchased a vinyl cutter last year, but that it wasn't yet ready for use. True? False? Something we can access this year?

**Comment by kristinashu** [comment]
Here is an idea for the vinyl locations and numbers https://redpen.io/p/ewf78d105e4368c2af
If this seems right, then I can figure out the sizes and amounts.

**Comment by kristinashu** [comment]
@marcwalsh here are some very rough estimates for vinyl dimensions.

**Vinyl for Stairs**
02mm x 100mm
quantity = 3

960mm x 100mm
quantity = 3

431mm x 100mm
quantity = 4

364mm x 100mm
quantity = 1

397mm x 100mm
quantity = 3

586mm x 100mm
quantity = 3

399mm x 100mm
quantity = 4

804mm x 100mm
quantity = 2

603mm x 100mm
quantity = 1

355mm x 100mm
quantity =  4

100mm x 100mm
quantity = 33

100mm x 100mm
quantity = 10

100mm x 100mm
quantity = 32

266mm x 100mm
quantity = 3

355mm x 100mm
quantity = 3

**Vinyl for Floor**

280mm x 76mm
quantity = 4

1301mm x 190mm
quantity = 1

523mm x 190mm
quantity = 3

750mm x 750mm
quantity = 1

1000mm x 1000mm
quantity = 1

Here are the sizes and quantities next to the artwork. 

<img width="734" alt="screen shot 2016-10-12 at 9 05 49 am" src="https://cloud.githubusercontent.com/assets/1068783/19317840/32175290-905b-11e6-9fad-2a962d70a703.png">
<img width="708" alt="screen shot 2016-10-12 at 9 05 59 am" src="https://cloud.githubusercontent.com/assets/1068783/19317842/321d283c-905b-11e6-9b59-55e590877762.png">
<img width="709" alt="screen shot 2016-10-12 at 9 06 06 am" src="https://cloud.githubusercontent.com/assets/1068783/19317841/321d2c88-905b-11e6-9fcc-dfb68a9d7a6c.png">

**Comment by Saallen** [comment]
According to above there are 94 pieces of vinyl for 9 stairwell- so an average there is 10 stickers on each stairwell. Presuming though there is less stickers the higher you go. Is there a placement map for all these? It would help understand the placement and flow 🔍

**Comment by kristinashu** [comment]
Numbers based on these maps https://redpen.io/p/ewf78d105e4368c2af (the pink dots represent where vinyl could go). 

General rules:
- staircase just before a Space would have the vinyl info (example: the staircase before level 4 would have vinyl for the Main Stage and Fuel the Movement)
- Spaces on the highest levels would need more vinyl (example: Fuel the Movement only has one vinyl because most people will make it to the 4th floor but Science has 4 vinyls so we can add it to stair cases 5, 6, 7, and 8 to draw people up)
- each Space will have a level number + arrow:
  <img width="883" alt="screen shot 2016-10-10 at 10 08 36 am" src="https://cloud.githubusercontent.com/assets/1068783/19244568/bdcd654e-8ed1-11e6-810a-4d37642146ae.png">

Hope that makes sense!

I've updates the dimensions in the comment above to reflect the updated design (all text is now in a solid square with text knocked out, like last year).

**Comment by kristinashu** [comment]
W00t! Sounds like we can print these off site!

**Comment by kristinashu** [comment]
@marcwalsh here are the print ready files https://drive.google.com/open?id=0B2irLVDJivhLSXY3THlfVjhpaFE

It has all the outlines artwork in one PDF, eps, and ai file.

These are all the pieces and quantities:
<img width="791" alt="screen shot 2016-10-13 at 1 22 54 pm" src="https://cloud.githubusercontent.com/assets/1068783/19365940/f3b01bdc-9149-11e6-9069-29d0dece013a.png">

Quantities are:
3 x MOZEX
2 x DILEMMAS IN CONNECTED SPACES
3 x OPEN SCIENCE
2 x YOUTH ZONE
2 x LOCALISATION
3 x DEMYSTIFY THE WEB
3 x OPEN BADGES
2 x DIGITAL ARTS AND CULTURE
2 x FUEL THE MOVEMENT
3 x JOURNALISM
33 x Arrows
10 x Diagonal Arrows
2 x M
1 x 1
2 x 2
2 x 3
2 x 4
4 x 5
4 x 6
4 x 7
6 x 8
3 x 9
3 x MOZHELP
2 x Large Arrows
2 x DIALOGUES & DEBATES

It should be printed on the same or similar magenta color as last year:
<img width="886" alt="84c6dfbc-69ee-11e6-8f6b-188aeac7f4d1" src="https://cloud.githubusercontent.com/assets/1068783/19365999/3623f0ce-914a-11e6-8947-526274bce82e.png">

**Comment by marcwalsh-zz** [comment]
Sent to printers! 💪

The two larger pieces are being printed 1.5m x 1.5m.
