### ISSUE TITLE
Discuss realtime Schedule update workflow

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/Mozfest2016_production#193]
@mmmavis – Let's do an update today of the schedule before @edrushka shares it with the whole world. 

And... let's talk about who can trigger updates and how they do it. For example, should they trigger update to staging via chat, check it, then trigger update to production? 

cc @edrushka

**Comment by edrushka** [comment]
One worry I have is that Dan and I are making many, many changes throughout the day. If we break something and don't see the schedule refreshed until EOD London time, it will be hard to know what change broke things. However, if we have the power to push changes live to production and we break things in the morning London-time, that's an entire day of a broken schedule 😱 

Maybe Dan and I get the power to push changes live to staging, and only Mavis can push to prod?

**Comment by mmmavis** [comment]
Relates to https://github.com/MozillaFoundation/mofo-devops/issues/415

I just talked to @cadecairos - We are thinking to have 2 mozbot commands available in Chat
1. One command to trigger the Python script (Python script gets data from Google Spreadsheet, formats it, and commits `sessions.json` to the`master` branch. In short, it updates the `staging` instance )
2. One command to merge `master` into `gh-pages` (which updates production site)

We thought about having a cron job to periodically push data to `staging` but we realized that might be redundant since it would still require a manual trigger to get data from `staging` to `production.`

How does this sound to you @edrushka @xmatthewx ? This way it requires us to make sure things look sane on `staging` before we refresh the `production` app.

@cadecairos is it possible that we have a private channel on Chat and we make the 2 mozbot commands available in only that private channel?

**Comment by edrushka** [comment]
I _think_ it sounds good. If there's a way to break the schedule with this system, I'll probably inadvertently discover it for you 😉

**Comment by cadecairos** [comment]
@mmmavis The command will have role-based authentication. i.e. I'll give people we want to allow to trigger the jobs the "jenkins" role.

I think I'm going to want to do the merge of master into gh-pages using jenkins too, I'll have to write that job.

**Comment by mmmavis** [comment]
@cadecairos Jenkin job to trigger updates to staging is done (`mofo-deploy-mozfest-app-staging`). I'm not sure how to link it to mozbot command. Could you lend a hand plz? 🍻

**Comment by xmatthewx** [comment]
@cadecairos – if an update breaks _everything_ while @mmmavis is sleeping or on a plane, can @edrushka and Dan (handle?) use the emergency on call number?

@edrushka & dan – if _everything_ breaks, first try: Google Sheets > File > Revision history. Roll back the changes & push them again via Chat command.

**Comment by cadecairos** [comment]
Yes, use the on-call email. I'll make sure that @gideonthomas is on-call while I'm in the air this coming Tuesday.

**Comment by mmmavis** [comment]
I think this was done. Closing.
