### ISSUE TITLE
Design retrospective

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#222]
In addition to our usual retrospective https://public.etherpad-mozilla.org/p/mozfest2016_designfeedback, @sabrinang and I will go through [all the assets](https://docs.google.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit#gid=1507933966) and add notes to each design asset ticket, this should make things easier for next year. We can include things like: images of how things turned out, how many we printed, was there enough, paper stock used... 

cc @xmatthewx

**Comment by kristinashu** [comment]
@sabrinang is making great progress in commenting on individual design tickets. 

We're added design related photos to a [Drive folder](https://drive.google.com/drive/folders/0B2irLVDJivhLQjJzbHdVSl8waGM?usp=sharing). If you took any photos, please add them there as well.

I've started a rough [blog post ](https://docs.google.com/a/mozilla.com/document/d/1AZLyI5ma8mW19RG0lrlJHCDDAW_4_TStG5tN0CP6Pm8/edit?usp=sharing) to recap design. @xmatthewx @sabrinang please add any photos, thoughts, suggestions, edits... you have!

**Comment by xmatthewx** [comment]
For our future selves, is the quickest view of notes and documentation of individual design items via the repo's [design label](https://github.com/MozillaFoundation/Mozfest2016_production/issues?q=is%3Aissue+label%3ADesign+is%3Aclosed+sort%3Aupdated-desc) (sorted by recently updated)? Or is there another doorway?

**Comment by kristinashu** [comment]
That or clicking on links in the spreadsheet https://docs.google.com/a/mozilla.com/spreadsheets/d/1J4LS4ILtG5x-jxwHEwGuDzXHRHC9IQM4t9fg2OUeRBs/edit?usp=sharing

**Comment by SpikeUK** [comment]
Can I be a Mister Grumpypants here please. Some of the design choices that were made were made without possibly considering the practical outcomes.
For example. Choosing to have ID cards with two punched holes and double ended lanyards so that the right side is always facing outwards. It took the volunteers twice as long to assemble the ID cards and lanyards as they had two clips per card to operate rather than just one.
For example. Not having swag bags as they are bad for the environment. It took about three times as long to assemble the printed items, the clip and the pen to be "just so" than it would have been to put the individual items in a jute bag
Assembling the ID cards and swag is the most tedious and mind-numbing part of MozFest - the local volunteers do this every year - please could you consider the people who have to spend **hours** clipping lanyards on to ID cards as part of you design process. Thank you!

**Comment by kristinashu** [comment]
Thanks for the notes @SpikeUK and for all the hard work the volunteers did! We'll add your notes to the relevant tickets so we can reference it next year.

**Comment by sabrinang** [comment]
For next year, we can have a more deliberate photo shot list for documenting design assets or specific shots we want to capture that would be handy for our design work in the future. The list can ensure we have clearer photos of assets, capturing more moments of people using the design, people engaged in activities for website use in mind or any staged photos needed etc. The spreadsheet could be used for this purpose with an extra column or it can be a simplified printed document that can be passed on to the official photographer too. The festival guide photos was a great request and we got lovely shots from it. We didn't miss much this year and there is a great collection of photos/media to be found online with #mozfest! Woohoo!

**Comment by kristinashu** [comment]
Good point @sabrinang! 

Blog post about design is up https://medium.com/mozilla-festival/designing-for-mozilla-festival-e398d65ec249#.1nt0qox7j

I think this is good to close!
