### ISSUE TITLE
Live Stream Supplier

### ISSUE THREAD

**Issue by marcwalsh** [MozillaFoundation/Mozfest2016_production#24]
Supplier for Live Stream as mentioned in #25 

Live stream of talks on the main stage as well as D&D in another space in the building. 
Stream needs to be sent to AirMozilla as well as the possibility of YouTube. (Yet to be decided if this is live or uploaded after.)
- [x] Scope of work drawn up #48
- [x] Suppliers researched
- [x] Three suppliers shortlisted and contacted for quotes and latest showreels
- [x] Contract drawn up

**Comment by marcwalsh-zz** [comment]
I have contacted two companies as well as asking for a quote in house from Ravensbourne.

The two companies are
- [Haus Pictures](http://hauspictures.com/)
- [Dosed](http://www.dosed.co.uk)

We are also looking to see if this can be kept entirely in house and using Event AV kit as well as MoCo production staff.

**Comment by marcwalsh-zz** [comment]
We're also requesting a quote from Ravensbourne on this, as well as looking into working with MoCo equipment and crew / MoCo equipment and Ravensbourne crew.

**Comment by mmmavis** [comment]
/cc myself @mmmavis and @cadecairos ~~(tl;dr, MozFest site needs to link out to a Facebook streaming page when the D&D speakers series start. We can't know the direct link ahead of time. We will have to turn off caching so that once the streaming goes live, we update MozFest site with the Facebook direct link and the site can reflect the URL change immediately.)~~

---

### Updates:

@cadecairos plz hold off on turning off cache. I just had a chat with @edrushka and @kristinashu - we are not planning on updating links on the fly at the event. Phew! 😄

**Comment by edrushka** [comment]
@marcwalsh can you please update this when the supplier contract is signed. I need to connect Liz from MoCo with the supplier.

**Comment by marcwalsh-zz** [comment]
@edrushka We're working with Mac and Kevin from AirMm. Dosed will be providing support with this, however the stream will be a shared responsibility. - hope that answers the question!
