### ISSUE TITLE
Design Festival Guide: Concept - Deadline Sept 13

### ISSUE THREAD

**Issue by edrushka** [MozillaFoundation/Mozfest2016_production#69]
This is the meta-bug for the MozFest 2016 Festival Guide design.

**Comment by kristinashu** [comment]
Festival Guide design brief is [here](https://docs.google.com/document/d/1Cz3kZSrwmvnaO8GDlTl8VTcvPjZ4TmjfVvaul8rhOvQ/edit#).

**Content to include and ticket where copy will be written:**
- Cover
- Table of contents
- Introduction: What is MozFest? #108 
- Key festival timings #109
- Mozilla’s 5 Key Issues #110
- Dialogues and Debates Speakers Series #111
- Spaces #112
- Space wrangler bios #56 
- Non-EN sessions #113
- Participation guidelines #114
- Network celebration/testimonial piece #115
- Back cover

(note: there will be a map will be an insert https://github.com/MozillaFoundation/Mozfest2016_production/issues/91)

While copy is being gathered, we can start to explore the guide format, dimensions, page number treatment, layout styles, photo treatments... 

[Last year's guide](https://redpen.io/p/qk2adb94ee9367c3cc) was a fold up poster but we would like this years to be more substantial and something we can show off year round.

We like the idea of using a clip instead of having to use a tote bag: 
![104bd2fbacfe9a5e4c545b49da8b0c8b](https://cloud.githubusercontent.com/assets/1068783/18214582/89983502-7102-11e6-8866-a28ddb44857b.jpg)

Here's an example of a cover from the style guide
<img width="638" alt="screen shot 2016-09-02 at 11 45 11 am" src="https://cloud.githubusercontent.com/assets/1068783/18214622/beb2e9b2-7102-11e6-9afb-5d1c8de221e4.png">

@sabrinang please add any inspiration you've come across here.

**Comment by kristinashu** [comment]
@edrushka @marcwalsh what is the new deadline for this?

**Comment by sabrinang** [comment]
Inspiration included in gslides: https://docs.google.com/presentation/d/1Wr2XK-ogr-72XnMqdmLU2Rf64S-5ctC23OimMwnsquY/edit#slide=id.g167ec3675c_0_0

<img width="1424" alt="screen shot 2016-09-02 at 2 04 09 pm" src="https://cloud.githubusercontent.com/assets/2492510/18218245/35e2ba68-7116-11e6-95d8-fe0adc35b767.png">
It would be great to have a festival guide with clip system so we can add inserts and pencils etc. to stay together without the tote

<img width="1422" alt="screen shot 2016-09-02 at 2 04 17 pm" src="https://cloud.githubusercontent.com/assets/2492510/18218248/385038ac-7116-11e6-8305-d2a874cbbfd4.png">
The clip itself can embrace the neon palette and we can consider clips that are multipurpose (bottle opener or money clip so they can use it after the festival)

<img width="1424" alt="screen shot 2016-09-02 at 2 04 26 pm" src="https://cloud.githubusercontent.com/assets/2492510/18218249/39e3ed44-7116-11e6-97f7-d268e987c669.png">
Here are some format ideas: the booklet can be smaller with a larger insert tucked to frame the cover design or the festival guide can be larger with a smaller insert on the outside playing off the design of the cover. Also, we can consider the guides doubling as a notebook and we can design space for contacts/people you have met so it is all in one place instead of the business cards last year.

**Comment by kristinashu** [comment]
**Overview of Deadlines:**
- Deliver concept [Carrie-Ann]: Sept 13
- Review & feedback on concept [MoFo Design]: Sept 15
- Content deadline [Erika]: Sept 20
- Deliver version 1 [Carrie-Ann]: Sept 20
- Design team review & feedback on 1st mock-up  [MoFo Design]: Sept 22
- Deliver version 2 (final) [Carrie-Ann]: Sept 27
- Design team review & feedback on 1st mock-up  [MoFo Design]: Sept 29
- Final Revisions [Carrie-Ann]: Oct 3
- Copyediting [Erika]: Oct 3-6
- Final copy edits [Carrie-Ann]: Oct 7-11
- Send to printers [Marc]: EOB Oct 11

**Comment by kristinashu** [comment]
Based on our meeting. We're adding concept and inspiration to the redpen: https://redpen.io/p/aq3ed683d65024fc8f

@Carrie-ann's next steps: 
1. A quick low-fi dump of copy, black on white … so fest organizers can see how text fits across all the pages. discover their mistakes. Add blocks for missing content...
2. A set of visual directions. Each could just be a cover and interior page. Focus on style, use of color, pattern. One direction could be an extension to the example in the style guide.

Could add some photos from last year https://www.flickr.com/photos/mozfest/albums/with/72157660181490099

**Comment by xmatthewx** [comment]
Hey team, the dimensions we discussed yesterday (240mm x 170mm) seem large to me. I'm curious what @sabrinang & @kristinashu think. In the past, we have had something that was pocket sized or notepad sized, maybe 150mm on the long side @Carrie-ann 

I'm not opposed to something larger and could be convinced, but let's discuss the pros and cons here.

**Comment by SpikeUK** [comment]
Could I please request that the Festival Guide not be made of too many individual parts - I will have to organise getting 1,800 (or so) of these assembled from the individual components by the Local Volunteers :(

**Comment by marcwalsh-zz** [comment]
Hey @SpikeUK - the festival guide will be a booklet that's printed. We won't be having swag bags this year, instead we will be building packs that include the festival guide, a couple of flyers, a sticker notepad and a pen and they'll be held together with a bulldog/binder clip.

Hopefully it shouldn't add too much time to what is normally allocated.

**Comment by SpikeUK** [comment]
Thanks @marcwalsh - I was thinking it was Swag Bag _and_ Festival Guide stack - I did not realise it was Festival Guide "instead of"..... ;-)
Thank you for putting me straight.
/me goes off totally rewrite Volunteer timetable

**Comment by kristinashu** [comment]
@Carrie-ann @xmatthewx I agree 240mm x 170mm is probably too big for something people will be carrying around but at the same time pocket size might not be big enough to house all the additional content we have this year. How about something in between? 

Here are a few examples of sizes to get a sense of scale:
The field notes are 90x140mm
Notebook 205x205 / Map 180x220 / Great 155x205
<img width="912" alt="screen shot 2016-09-16 at 9 30 20 am" src="https://cloud.githubusercontent.com/assets/1068783/18593438/40a3b9f4-7bf0-11e6-9b4c-d3d3dd067d60.png">

**Comment by Carrie-ann** [comment]
@kristinashu @xmatthewx I do think pocket size could be a bit too small for the amount of content we have for the guide (just based on what I have seen so far). I'm just considering that if we want to possibly have a small booklet/spread inside to emphasise the layering concept we would want the main pages to be big enough to allow it to fit. 

What about an A5 size (148 x 210 mm) or something around close to that scale? That is quite a common (and cheapish) size to work with and I personally find it quite nice to hold. 

I also remember in a conversation in one of the meeting someone mentioning that they would like the brochure to kinda like a zine in feel. The ones I have are quite loose (one paper stock for cover and inside) are are not very small. 

Let me know your thoughts. :)

**Comment by kristinashu** [comment]
Thanks @Carrie-ann, 148 x 210 mm sounds great! 

I only vaguely remember the zine comment but I wouldn't worry about it too much, it was probably just a passing comment.

**Comment by sabrinang** [comment]
Yeah, I think A5 size would be great and allow for small spreads inside. 

@Carrie-ann Do you know what size are these small spreads? I think it can inform the size for our notepads (https://github.com/MozillaFoundation/Mozfest2016_production/issues/150) and would be sweet if the proportions of this works with the festival guide when bundled together with the clip.

**Comment by kristinashu** [comment]
Closing this ticket, we've moved on to https://github.com/MozillaFoundation/Mozfest2016_production/issues/135
