### ISSUE TITLE
Utilizing Ti.to questions for measuring impact

### ISSUE THREAD

**Issue by Saallen** [MozillaFoundation/Mozfest2016_production#7]
Using the registration platform as a measuring tool for impact 
We have about 10 registration forms each can be asked the same questions or different questions.

I would like to open the ticket page the same day as the call for proposals- 1st June.
So we need to decide what questions we need to ask to get responses we can use as metric gauging  responses.
Looking for adivce from @adamlofting on the types of questions we should ask

**Comment by Saallen** [comment]
Last years questions 
* Is this your first MozFest? 
* Will you attend both days with your group or one day on your own? 
* Who has invited you to join us for Mozilla Festival 2015 
* What themes are you interested in 
*  What themes are you interested in?
* What do you hope to get out of the festival? 
* Do you work for Mozilla or are you a contributor? 
* If you are an awesome contributor who invited you to MozFest this year ?

Logistical questions

* What space are you facilitating in? 
* What school or learning institute are you representing at Mozilla Festival 2015? 
* What course do you study at Ravensbourne? 
* Please name the guardian or school you will be attending with?
* If you work for Mozilla what team are you representing at the festival?
* Are any of your guests under the age of 16 years? If yes, how many?

**Comment by adamlofting** [comment]
We should also ask for:
* Twitter handle @...........
* Github handle @...........

With some text like: *if you use Twitter or Github, we'd love to connect with you over the weekend and help you connect with new people*. 

The questions from last year are great, but here are some possible tweaks.

* If you've been to Mozfest before, which years? 
  * 2012, 2013, etc
* I'm planning to attend:
  * [ ] Friday (evening), [  ] Saturday, [ ] Sunday
* Which of these Mozilla priority issues matters most to you? 
  * Work with @KevZawacki @samanthaburton on the language / hashtags around this
* What do you hope to get out of the festival?
  * Could add some checkbox options here: show my work, meet new people, join a project, learn more about Mozilla, work on an existing project, etc
* Did someone invite / recommend you come to Mozfest? If yes, who?

**Comment by samanthaburton** [comment]
re: hashtags - the language has changed slightly since MozRetreat (as shared at the [Issues Agenda Town Hall](https://docs.google.com/presentation/d/1JEsGpJRvp6ROxZbpSWAzq_jdzVKHpB2es-TS-BkAVmA/edit#slide=id.g13f4c7b5cc_0_0)) so the priority issues & suggested hashtags are now:

**Online Privacy + Security** #privacy
People understand and can meaningfully control how their data is collected and used online, and trust that it’s safe. In parallel, companies and governments work to protect our data and enhance our ownership over our digital identities.

**Open Innovation** #open
Open is the default: open source and open standards continue to be at the heart of the Internet, and influence organizations and industries products, policies and practices. As a result, entrepreneurs and everyday Internet users  can create, innovate and compete online without asking permission.

**Decentralization** #decentralized
The technologies and platforms people use every day are interoperable and based on open standards. And people expect and demand systems that allow seamless flow and transfer of information and content.

**Web Literacy** #weblit
People have the skills to read, write and participate in the digital world. Together, these informed digital citizens move beyond just consuming content, to creating, shaping and defending the web

**Digital Inclusion** #inclusion
People everywhere can access and have the opportunity to participate in building the entire Internet. Subsequently, everyone on the Internet has the opportunity to access and shape our digital world. The internet reflects the diversity of the people who use it.

**Comment by Saallen** [comment]
Hi @adamlofting @samanthaburton 
We would have to offer links out to these issues so ppl understand what they are picking as relevant to them. Is there a home for these issue hashtags? or a blog post to link to?

**Comment by samanthaburton** [comment]
We're still working on figuring out their online home, for now they live in this sharable GoogleDoc - https://docs.google.com/document/d/1cLC3zpcUaqqordvmHOTpcRUiyNqlBf1RIordVLZ9WIg/edit

**Comment by edrushka** [comment]
Closing as this has been implemented. Here are the questions that were included on the ti.to form:

1) I'm okay with receiving updates about MozFest.
2) What do you hope to get out of the festival?
- Meet new people
- Showcase my work
- Learn more about Mozilla
- Work on an existing project
- Learn how to work open
- Join a project
- I don't know
3) MozFest is designed around some key issues the Internet is facing. Which of these issues matters most to you?
- Online Privacy + Security #privacy
- Open Innovation #open
- Decentralization #decentralized
- Web Literacy #weblit
- Digital Inclusion #web4all
- I don't know
4) Have you been to MozFest before?
5) Did someone invite or recommend you come to MozFest?
6) What is your Twitter handle?
7) What is your Github handle?
