### ISSUE TITLE
Design template for keynote speaker slides - Deadline Oct 14

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#86]
#### Info:

Create a few background images. Will be very similar to #87
#### Last year's:
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/286
- Working files in Drive https://drive.google.com/open?id=0B2irLVDJivhLcDItdFRvQ2xab0E

<img width="1075" alt="screen shot 2016-08-23 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/1068783/17943227/5da29880-69ef-11e6-80af-b965dd3b9f8b.png">

**Comment by kristinashu** [comment]
@edrushka @marcwalsh are we having keynote speakers this year or just the D&D speakers? If we are still having keynote speakers, would it happen on the Main Stage or the D&D stage?

**Comment by edrushka** [comment]
We are still having speakers on Saturday and Sunday:

Saturday morning, 9 a.m. // 20-30 minutes 
Mark Surman kicks off the festival by introducing the key issues and threats facing Mozilla and the broader open Internet movement. 

Mark’s inspirational/thematic talk will be followed by a brief housekeeping talk by Gunner. Gunner introduces the Spaces, the D+D space, and how to participate

Sunday morning, 10 a.m. // 30-40 minutes
Mitchell delivers the story of Mozilla and MozFest, and what’s ahead. 
We might have someone join Mitchell, like a former, big-name Mozillian, or a spokesperson from a like-minded organization.

Let's assume we'll have to prepare slides for both Mark and Mitchell (and the possible special guest joining Mitchell) until we hear otherwise.

**Comment by sabrinang** [comment]
We will be borrowing layouts from the [one web speaker's template](https://docs.google.com/presentation/d/1LxSvUaG5BTq8Zv4os_Qmgkgb204LiXWM3RoABVE-bxE/edit#slide=id.g1865d99020_4_107) or [speaker series bookend slides](https://docs.google.com/presentation/d/1ztrY9GBVc10nSUFFXxE1d0UZZDRNRhCAZ9-cUfz60a0/edit#slide=id.g184b5001c6_0_66) from https://github.com/MozillaFoundation/Mozfest2016_production/issues/87 to be used for these keynote speaker slides too. In the past it has been common for full image slides to be used so we may not need the layouts but maybe a mozfest logo present on each slide.

@edrushka Let us know if you have any more tips on how we can finish these slides sooner than later

**Comment by edrushka** [comment]
I have no updates on Mark's presentation yet. If he's ok with it, I'm fine with using full image slides (since the mainstage is heavily branded already) and bookending with one of the assets listed above.

Mark likely won't finalize his presentation until next Thur/Fri so let's go with the simplest design to implement last-minute. FYI @Lottarao is helping to coordinate Mark's presentation.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

For Saturday's opening session on the main stage, Mark's biography slide appear as he is introduced and before he appears #mozfest slide is used. As he speaks, [ProPresenter social feed slides](https://github.com/MozillaFoundation/Mozfest2016_production/issues/214) showcase tweets on the #mozfest experience. The slides were adapted from the dialogue and debates bookend slides https://github.com/MozillaFoundation/Mozfest2016_production/issues/87.

With festival notes follwing after, Gunner shared a few words being accompanied by the #mozfest hastag and ProPresenter tweet slides again.

On Air Mozilla and Facebook live, the #mozfest slide is fullscreen before the speakers emerge. The screens are not seen and only wide shots show glimpses of the two monitors on either side of the stage.

![mozfest-documentation-photos_opening-mark-slides](https://cloud.githubusercontent.com/assets/2492510/20081634/bd01cfac-a505-11e6-9890-a26cf5ee0ca3.png)
<img width="1438" alt="screen shot 2016-11-07 at 4 33 10 pm" src="https://cloud.githubusercontent.com/assets/2492510/20082034/1fdeb192-a508-11e6-8280-a85007df6d1a.png">
