### ISSUE TITLE
Design template for D&D slides - Deadline Oct 14

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/Mozfest2016_production#87]
#### Info:

New to this year. Most speakers will be on this stages instead of the main stage.

Create a few background images.

Template slide for: 
- MozFest 2016 intro
- 5 issues
- speaker into
- example of image layout
- placeholder while someone is speaking and doesn't have slides
- thank you
- ...

Related to main stages slides https://github.com/MozillaFoundation/Mozfest2016_production/issues/86 and stage design https://github.com/MozillaFoundation/Mozfest2016_production/issues/103

Last year's is a good content reference https://docs.google.com/a/mozilla.com/presentation/d/1--8UMoYpWzB6O0AG4AosxzKRnn3k4t17QyxrdjC5PYU/edit?usp=sharing

Please note, this is template only. Not implementation for each speaker. – @xmatthewx
#### Last year's:
- GitHub ticket https://github.com/mozilla/mozillafestival.org/issues/286
- Working files in Drive https://drive.google.com/open?id=0B2irLVDJivhLcDItdFRvQ2xab0E

<img width="1075" alt="screen shot 2016-08-23 at 1 46 39 pm" src="https://cloud.githubusercontent.com/assets/1068783/17943227/5da29880-69ef-11e6-80af-b965dd3b9f8b.png">

**Comment by sabrinang** [comment]
Work in progress on google slides here: https://docs.google.com/a/mozilla.com/presentation/d/1ztrY9GBVc10nSUFFXxE1d0UZZDRNRhCAZ9-cUfz60a0/edit?usp=sharing
<img width="1153" alt="screen shot 2016-10-05 at 6 01 24 pm" src="https://cloud.githubusercontent.com/assets/2492510/19137024/e25bda1c-8b25-11e6-8449-f37b2cb16570.png">
- I'll continue to refine some layout options and set type for pages with lots of text/lists and then will make into master slides

**Comment by xmatthewx** [comment]
This is fantastic. Really really beautiful. It's extremely extensive. Let's wrap this up soon with a few content templates and then call it done (text, list, image, image+text). Constraints will be more helpful for non-designers.

@KevZawacki – I believe we should expect that many speakers will provide slides of their own design. We can insert them between our title slides. There are way too many speakers for us to coordinate and confirm all their slides. Some will have an aesthetic that supports their specific content and won't be able to use our content templates. Does this all ring true to you?

**Comment by KevZawacki** [comment]
@xmatthewx Right on. I'm happy with the majority of speakers using these as bookends.

**Comment by sabrinang** [comment]
@xmatthewx I cleaned up the slides made master slides and included all the speakers from the [playbook](https://docs.google.com/document/d/14VXDQcdKjOztX62HxYbnHXrPjwD-xR3ATY03KcsPVSo/edit). If we are using these as bookends I didn't make many content templates assuming that speakers will place their own slides in between.
<img width="1053" alt="screen shot 2016-10-14 at 4 01 30 pm" src="https://cloud.githubusercontent.com/assets/2492510/19404967/7f0c41fa-9227-11e6-9be1-fe5988a36ef3.png">

@KevZawacki Do you have the speakers slides? Let me know how we go about integrating the ones that do have slides.

**Comment by KevZawacki** [comment]
@sabrinang I don't have any speaker slides at the moment. And unfortunately, don't anticipate receiving them until the last second :-/

What do we think about sending these to speakers proactively so they can integrate into their decks?

@edrushka

**Comment by edrushka** [comment]
+1 to doing whatever we can to be proactive. 

 @xmatthewx did you say it looks odd when speaker's slides are branded with the festival branding? Did you mean we should we just let their decks be unbranded?

**Comment by xmatthewx** [comment]
I recommend we send black/gray/white slide templates for text, bullets, text+image that have our diagonal, but no logo and no bright colors. 

Our bright colors can signal that a talk is over or about to begin. 

This will minimize labor and give us flexibility for speakers who have stylized slides of their own.

**Comment by xmatthewx** [comment]
In terms of process, I'm glad to have a designer help fix problems and add polish .... but I'd prefer it if they were not in the role of collating slides from speakers. It'll introduce an inefficient layer of communication. Make sense?

**Comment by edrushka** [comment]
That works for me. Does that mean the design team will create a template slide with the diagonals in the background that we can share with speakers? Or should we wait, and add the diagonals after?

**Comment by xmatthewx** [comment]
Edit: we'll just offer white Opens Sans text on gray or black. No branding for speaker slides.

**Comment by KevZawacki** [comment]
@xmatthewx This makes sense and sounds good. So it seems the next steps are:

-- Designers send black/white slide templates to Kevin, who will in turn send to speakers
-- Designers send colored bookend slides to Kevin and Erika, who will broadcast in-between talks

Correct?

**Comment by xmatthewx** [comment]
If possible, I'd recommend combining speakers slides with the slides prepared by Sabrina. So you can present from a single laptop, nice and smoothly.

**Comment by sabrinang** [comment]
Speaker's Template: https://docs.google.com/a/mozilla.com/presentation/d/1LxSvUaG5BTq8Zv4os_Qmgkgb204LiXWM3RoABVE-bxE/edit?usp=sharing

<img width="905" alt="screen shot 2016-10-20 at 2 03 59 pm" src="https://cloud.githubusercontent.com/assets/2492510/19578175/709f59ca-96cf-11e6-8cc4-e5e0094e8e42.png">
@xmatthewx @KevZawacki Do you have any feedback to revise this slide template? It's a generic template (so it is not branded) but with one web inspired angle and using the blue, teal and yellow (highlight) since black and grey felt out of place and so that I can reuse this template for https://github.com/MozillaFoundation/Mozfest2016_production/issues/86 too

**Comment by xmatthewx** [comment]
Looks very good. I dropped in a few small comments. 

We should decide whether or not to allow powerpoint. I fear import issues. If I get a vote, I vote no.

**Comment by sabrinang** [comment]
Thanks for the feedback @xmatthewx. 

I removed the text about the powerpoint to not give them any ideas or suggest powerpoint but if the speaker is keen on using powerpoint or already has slides done their presentation in powerpoint we can't stop them but it isn't difficult to import for us to include as gslides. 

The slide itself has placeholder content to demonstrate the master slides so I made the name/bio content more generic now since it just uses a blank slide. I included a helpful slide tip on the background image slide to help users. If the speaker isn't great with using gslides I suspect they'll use the placeholder slides and not the blank master slides to build their slides anyway or however they wish to support their talk's content.

**Comment by edrushka** [comment]
Whooooa! This is amazing!! Did you write all this content yourself?!?! This is way more fancy than I ever expected, so R++ from me!!

**Comment by KevZawacki** [comment]
@sabrinang This is **stunning**! Many, many thanks. 

Are we ready to share with our speakers / do we need to update any permissions?

**Comment by xmatthewx** [comment]
I think it's good to go, but maybe wait until @sabrinang arrives and gives the thumbs up. 
- I set permission to allow anyone to View, not Edit. 
- I confirmed they will still have the option to use _**File > Make a copy**_. 
- I made some edits to the instructions slide and move that to the first slide.

**Comment by sabrinang** [comment]
:+1: Thumbs up from me and permissions are good to go. 

Thanks @xmatthewx for reviewing and I also added to the revised instructions slides. @edrushka I didn't write most of the placeholder content (since it'll be deleted anyway), I adapted a [free template](www.slidescarnival.com) to be customized to our aesthetic and needs to help save time to make the quick turnaround :sweat_smile:

**Comment by xmatthewx** [comment]
@sabrinang – are we going to delete the slides like you suggested (keeping just instructions and maybe title slide). Then let people use the Add-New-Slide-with-Layout? I think we should before we send it out. I think it's less likely to overwhelm users.

**Comment by sabrinang** [comment]
@xmatthewx Sorry for the confusion if I suggested to delete slides, I think it is best to just leave it as is so the shapes, charts, illustrations are accessible to them (they won't be on layout slides) I just wanted them to be aware they have the option to start with bare layouts instead of just editing placeholder content.

**Comment by sabrinang** [comment]
## Post MozFest Documentation

For the various speaker series on the live dialogues and debates stage, a large monitor showcases the speaker series opening/closing ("bookend") slides with the other monitor displaying a live transcription feed.

The speaker series info, one web title, biography, q&a and thank you slides were used to accompany the presenter's own slides. The slide moderator toggled between slides seamlessly and was able to customize the slides _(example: addition of Mark & Mitchell biography slide below)_.

Also, the speaker's template was available for presenters to use to put in their own content. In the example below, Brian Behlendorf utilized this template in his talk.

On [Air Mozilla](https://air.mozilla.org/channels/mozfest-2016/) and [Facebook live](https://www.facebook.com/mozilla/videos?ref=page_internal) videos, the presenter's slides are superimposed on the video of the speaker and static image background. Introductory bookend slides are sometimes seen fullscreen.

![mozfest-documentation-photos_dd-slides](https://cloud.githubusercontent.com/assets/2492510/20081373/0f5b4ae6-a504-11e6-923b-ad5bd054a093.png)
